

function HandlePushCommand(segment, index)
    indexInt=parse(Int64, index)
    println(newFile, "//push "*segment*" "*index)
    if(segment=="argument")
        println(newFile, "@"*index)
        println(newFile, "D=A")
        println(newFile, "@"*"ARG")
        println(newFile, "A=M+D")
        println(newFile, "D=M")
        println(newFile, "@SP")
        println(newFile, "A=M")
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M+1")
    elseif(segment=="local")
        println(newFile, "@"*index)
        println(newFile, "D=A")
        println(newFile, "@"*"LCL")
        println(newFile, "A=M+D")
        println(newFile, "D=M")
        println(newFile, "@SP")
        println(newFile, "A=M")
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M+1")
    elseif(segment=="static")
        println(newFile, "@classA."*index)
        println(newFile, "D=M")
        println(newFile, "@SP")
        println(newFile, "A=M")
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M+1")
    elseif(segment=="constant")
        println(newFile, "@"*index)
        println(newFile, "D=A")
        println(newFile, "@SP")
        println(newFile, "A=M")
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M+1")
    elseif(segment=="this")
        println(newFile, "@"*index)
        println(newFile, "D=A")
        println(newFile, "@"*"THIS")
        println(newFile, "A=M+D")
        println(newFile, "D=M")
        println(newFile, "@SP")
        println(newFile, "A=M")
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M+1")
    elseif(segment=="that")
        println(newFile, "@"*index)
        println(newFile, "D=A")
        println(newFile, "@"*"THAT")
        println(newFile, "A=M+D")
        println(newFile, "D=M")
        println(newFile, "@SP")
        println(newFile, "A=M")
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M+1")
    elseif(segment=="pointer")
        if(indexInt==0)
            println(newFile, "@"*"THIS")
        elseif(indexInt==1)
            println(newFile, "@"*"THAT")
        end
        println(newFile, "D=M")
        println(newFile, "@SP")
        println(newFile, "A=M")
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M+1")
    elseif(segment=="temp")
        println(newFile, "@"*string(indexInt+5))
        println(newFile, "D=M")
        println(newFile, "@SP")
        println(newFile, "A=M")
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M+1")
    end

end


function HandlePopCommand(segment, index)
    indexInt=parse(Int64, index)
    println(newFile, "//pop "*segment*" "*index)
    if(segment=="argument")
        println(newFile, "@SP")
        println(newFile, "A=M-1")
        println(newFile, "D=M")
        println(newFile, "@"*"ARG")
        println(newFile, "A=M")
        for i in 1:indexInt
            println(newFile, "A=A+1")
        end
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M-1")
    elseif(segment=="local")
        println(newFile, "@SP")
        println(newFile, "A=M-1")
        println(newFile, "D=M")
        println(newFile, "@"*"LCL")
        println(newFile, "A=M")
        for i in 1:indexInt
            println(newFile, "A=A+1")
        end
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M-1")
    elseif(segment=="static")
        println(newFile, "@SP")
        println(newFile, "M=M-1")
        println(newFile, "A=M")
        println(newFile, "D=M")
        println(newFile, "@classA."*index)
        println(newFile, "M=D")
    elseif(segment=="this")
        println(newFile, "@SP")
        println(newFile, "A=M-1")
        println(newFile, "D=M")
        println(newFile, "@"*"THIS")
        println(newFile, "A=M")
        for i in 1:indexInt
            println(newFile, "A=A+1")
        end
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M-1")
    elseif(segment=="that")
        println(newFile, "@SP")
        println(newFile, "A=M-1")
        println(newFile, "D=M")
        println(newFile, "@"*"THAT")
        println(newFile, "A=M")
        for i in 1:indexInt
            println(newFile, "A=A+1")
        end
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M-1")
    elseif(segment=="pointer")
        println(newFile, "@SP")
        println(newFile, "A=M-1")
        println(newFile, "D=M")
        if(indexInt==0)
            println(newFile, "@"*"THIS")
        elseif(indexInt==1)
            println(newFile, "@"*"THAT")
        end
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M-1")
    elseif(segment=="temp")
        println(newFile, "@SP")
        println(newFile, "A=M-1")
        println(newFile, "D=M")
        println(newFile, "@"*string(indexInt+5))
        println(newFile, "M=D")
        println(newFile, "@SP")
        println(newFile, "M=M-1")
    end
end




function HandleAddCommand()
    println(newFile, "//add")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "D=M")
    println(newFile, "A=A-1")
    println(newFile, "M=M+D")
    println(newFile, "@SP")
    println(newFile, "M=M-1")
end


function HandleSubCommand()
    println(newFile, "//sub")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "D=M")
    println(newFile, "A=A-1")
    println(newFile, "M=M-D")
    println(newFile, "@SP")
    println(newFile, "M=M-1")
end


function HandleNegCommand()
    println(newFile, "//neg")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "M=-M")
end


function HandleEqCommand()
    global counterTrue
    global counterFalse
    counterTrueString=string(counterTrue)
    counterFalseString=string(counterFalse)
    println(newFile, "//eq")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "D=M")
    println(newFile, "A=A-1")
    println(newFile, "D=M-D")
    println(newFile, "@IF_TRUE"*counterTrueString)
    println(newFile, "D;JEQ")
    println(newFile, "D=0")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "A=A-1")
    println(newFile, "M=D")
    println(newFile, "@IF_FALSE"*counterFalseString)
    println(newFile, "0;JMP")
    println(newFile, "(IF_TRUE"*counterTrueString*")")
    counterTrue+=1
    println(newFile, "D=-1")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "A=A-1")
    println(newFile, "M=D")
    println(newFile, "(IF_FALSE"*counterFalseString*")")
    counterFalse+=1
    println(newFile, "@SP")
    println(newFile, "M=M-1")
end


function HandleGtCommand()
    global counterTrue
    global counterFalse
    counterTrueString=string(counterTrue)
    counterFalseString=string(counterFalse)
    println(newFile, "//gt")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "D=M")
    println(newFile, "A=A-1")
    println(newFile, "D=M-D")
    println(newFile, "@IF_TRUE"*counterTrueString)
    println(newFile, "D;JGT")
    println(newFile, "D=0")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "A=A-1")
    println(newFile, "M=D")
    println(newFile, "@IF_FALSE"*counterFalseString)
    println(newFile, "0;JMP")
    println(newFile, "(IF_TRUE"*counterTrueString*")")
    counterTrue+=1
    println(newFile, "D=-1")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "A=A-1")
    println(newFile, "M=D")
    println(newFile, "(IF_FALSE"*counterFalseString*")")
    counterFalse+=1
    println(newFile, "@SP")
    println(newFile, "M=M-1")
end


function HandleLtCommand()
    global counterTrue
    global counterFalse
    counterTrueString=string(counterTrue)
    counterFalseString=string(counterFalse)
    println(newFile, "//lt")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "D=M")
    println(newFile, "A=A-1")
    println(newFile, "D=M-D")
    println(newFile, "@IF_TRUE"*counterTrueString)
    println(newFile, "D;JLT")
    println(newFile, "D=0")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "A=A-1")
    println(newFile, "M=D")
    println(newFile, "@IF_FALSE"*counterFalseString)
    println(newFile, "0;JMP")
    println(newFile, "(IF_TRUE"*counterTrueString*")")
    counterTrue+=1
    println(newFile, "D=-1")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "A=A-1")
    println(newFile, "M=D")
    println(newFile, "(IF_FALSE"*counterFalseString*")")
    counterFalse+=1
    println(newFile, "@SP")
    println(newFile, "M=M-1")
end


function HandleAndCommand()
    println(newFile, "//and")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "D=M")
    println(newFile, "A=A-1")
    println(newFile, "M=D&M")
    println(newFile, "@SP")
    println(newFile, "M=M-1")
end


function HandleOrCommand()
    println(newFile, "//or")
    println(newFile, "//and")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "D=M")
    println(newFile, "A=A-1")
    println(newFile, "M=D|M")
    println(newFile, "@SP")
    println(newFile, "M=M-1")

end


function HandleNotCommand()
    println(newFile, "//not")
    println(newFile, "@SP")
    println(newFile, "A=M-1")
    println(newFile, "M=!M")

end


    global counterTrue=0
    global counterFalse=0
    path=input()
    arr=split(path, "\\")
    newFile=open(path*"\\"*arr[end]*".asm", "w")
    files=readdir(path)
    for file in files
        if endswith(file, ".vm")
            currentfile=open(path*'\\'*file, "r")
            for line in readlines(currentfile)
                if !(startswith(file, "//"))
                    words=split(line, " ")
                    if(words[1]=="push")
                        HandlePushCommand(words[2], words[3])
                    elseif(words[1]=="pop")
                        HandlePopCommand(words[2], words[3])
                    elseif(words[1]=="add")
                        HandleAddCommand()
                    elseif(words[1]=="sub")
                        HandleSubCommand()
                    elseif(words[1]=="neg")
                        HandleNegCommand()
                    elseif(words[1]=="eq")
                        HandleEqCommand()
                    elseif(words[1]=="lt")
                        HandleLtCommand()
                    elseif(words[1]=="gt")
                        HandleGtCommand()
                    elseif(words[1]=="and")
                        HandleAndCommand()
                    elseif(words[1]=="or")
                        HandleOrCommand()
                    elseif(words[1]=="not")
                        HandleNotCommand()
                    end
                end
            end
            close(currentfile)
        end
    end
    close(newFile)
